addpath(genpath('/cluster/home/vignesh/synapseProject/interfaces/featureComputation/'));
mcc -m featGate.m cbi_bagimg.m ...
fourierMellin.m ...
createGabor.m gistGabor.m prefilt.m ...
cont.m getMapping.m lbp.m ...
computeRadon.m getEdgeFeatures.m makeBarFilters.m radonLikeFeaturesDemo.m ...
rayFeature.m cutImg.m ... 
cbi_fsv.m cbi_log.m computeSVMoments.m ...
cbi_gabor.m cbi_gabordictionary.m convTexture.m ... 
makeRFSfilters.m makeLMfilters.m vrl_imfilter.m;
