% Compile FeaturesCompute

addpath(genpath('/cluster/home/retinamap/synapseProject/interfaces/featureComputation/'));
addpath('/cluster/home/retinamap/synapseProject/source/synapseDetector/benchmark/src'); 
addpath('/cluster/home/retinamap/synapseProject/source/synapseDetector/benchmark/data');

mcc -m FeaturesCompute.m cbi_bagimg.m ...
fourierMellin.m ...
createGabor.m gistGabor.m prefilt.m ...
cont.m getMapping.m lbp.m ...
computeRadon.m getEdgeFeatures.m makeBarFilters.m radonLikeFeaturesDemo.m ...
rayFeature.m cutImg.m ... 
cbi_fsv.m cbi_log.m computeSVMoments.m ...
cbi_gabor.m cbi_gabordictionary.m convTexture.m ... 
makeRFSfilters.m makeLMfilters.m vrl_imfilter.m;


% mcc -m FeaturesCompute_unstable.m cbi_bagimg.m ...
% fourierMellin.m ...
% createGabor.m gistGabor.m prefilt.m ...
% cont.m getMapping.m lbp.m ...
% computeRadon.m getEdgeFeatures.m makeBarFilters.m radonLikeFeaturesDemo.m ...
% rayFeature.m cutImg.m ... 
% cbi_fsv.m cbi_log.m computeSVMoments.m ...
% cbi_gabor.m cbi_gabordictionary.m convTexture.m ... 
% makeRFSfilters.m makeLMfilters.m vrl_imfilter.m;